# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js app to Azure Web App - speechdiary(staging)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test client
      working-directory: Client
      run: |
        npm install
        npm run build --if-present
        
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
        
                
    - name: azure-blob-copy-action
      # You may pin to the exact commit or the version.
      # uses: ulaval/azure-blob-copy-action@a5589c66042be9a15da7cc2a28e63adc3a42af3a
      uses: ulaval/azure-blob-copy-action@v1
      with:
        # Azure Blob Storage connection string
        connection_string: DefaultEndpointsProtocol=https;AccountName=speechdiarybuilds;AccountKey=ZSaiwNZpWfFRkf9EV0aNwl6VklFJMvqRDWj+jLzy1vLhdo478bJZ8VlIUE8q2YX7HMS/LOTyTxhBlI8KIo0FSA==;EndpointSuffix=core.windows.net
        
        # Azure Blob Storage container name
        container_name: builds
        


    
